name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install smth
        run: |
          make -f makefile install
      
      - name: Build application
        run: |
          make -f makefile run
          
      - name: Test smth
        run: |
          make -f makefile test